# Generated by Django 3.2.9 on 2022-09-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_auto_20220825_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedauthuser',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('admins', 'Admin')], max_length=200, null=True),
        ),
    ]
